import type { PlanRef, VerificationResult } from "@marathon/core";
import { isVerificationGreen } from "./verification";

export interface PrBodyInput {
  summary: string;
  planRef: PlanRef;
  verification: VerificationResult[];
  openQuestions?: string[];
  taskId: string;
}

/**
 * The PR body template (design §29.5): summary → plan link → verification
 * results → open questions → Marathon task link → provenance footer. The PR
 * *is* the review surface; it must carry everything a reviewer needs without
 * opening Marathon.
 */
export function buildPrBody(input: PrBodyInput): string {
  const { planRef } = input;
  const planUrl = `https://github.com/${planRef.repo}/blob/${planRef.mergeCommitSha}/${planRef.docPath}`;
  const parts: string[] = [input.summary.trim()];

  parts.push(`## Plan\n\n[\`${planRef.docPath}\`](${planUrl}) @ \`${planRef.mergeCommitSha.slice(0, 12)}\``);

  if (input.verification.length > 0) {
    const rows = input.verification.map(
      (v) => `- ${v.exitCode === 0 ? "✅" : "❌"} \`${v.command}\` (exit ${v.exitCode}) — ${v.summary}`,
    );
    parts.push(`## Verification\n\n${rows.join("\n")}`);
  } else {
    parts.push(`## Verification\n\n⚠️ No verification commands were run.`);
  }
  if (!isVerificationGreen(input.verification) && input.verification.some((v) => v.exitCode !== 0)) {
    parts.push(`> ⚠️ Verification is not green — delivered as a draft (\`marathon:unverified\`).`);
  }

  if (input.openQuestions?.length) {
    parts.push(`## Open questions\n\n${input.openQuestions.map((q) => `- ${q}`).join("\n")}`);
  }

  parts.push(`---\nMarathon-Task: \`${input.taskId}\`\n_Generated by Marathon from the merged plan; nothing lands without a human merge._`);
  return parts.join("\n\n");
}
